version: '3.8'

services:
  app:
    container_name: sodacore-demo
    image: sodacore-demo:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    # environment:
    #   SODACORE_ENV: "production"
    #   DATABASE_URL: "file:./dev.db"
    #   HTTP_PORT: "8080"
    #   CLI_PASSWORD: "<YOUR_CLI_PASSWORD>"
    #   DISCORD_TOKEN: "<YOUR_DISCORD_TOKEN>"
    #   DISCORD_CLIENT_ID: "<YOUR_DISCORD_CLIENT_ID>"
    #   DISCORD_GUILD_ID: "<YOUR_DISCORD_GUILD_ID>"
    restart: unless-stopped
